name = "recipe-solasido"
compatibility_date = "2026-02-11"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "dopamine_db"
database_id = "5769fa3c-4809-423b-ade5-0a5607ad0b0f"

[[r2_buckets]]
binding = "IMAGES"
bucket_name = "solasido-static-assets"
