export const SITE_NAME = '우당탕탕 여우의 일상툰'
export const SITE_DESCRIPTION = '우당탕탕 여우의 소소한 일상 이야기'
export const SITE_URL = 'https://dopamine.solasido.world'
export const PUBLISHER_NAME = 'solasido.world'
export const AUTHOR_NAME = '여우 YEOWOO'
export const AUTHOR_INSTAGRAM_URL = 'https://instagram.com/solasido.pamine'
